### ISSUE TITLE
Add a strict object validator

### ISSUE THREAD

**Issue by carloslfu** [AlexGalays/validation.ts#1]
Hi @AlexGalays , I am using `validator.ts` inside a project and it is so great. While using it, I find it useful to have an strict object validator, I have implemented it based on the `ObjectValidator` so you can see it working [here](https://stackblitz.com/edit/typescript-strict-object-validator?file=index.ts). What I mean with strict is that if the object has more properties it is considered as a error. If you want I can make a PR.

**Comment by AlexGalays** [comment]
Hello @carloslfu 

yes, I like the idea; I know it comes in handy once in a while.

A PR would be great!

**Comment by AlexGalays** [comment]
Do you have a use case in mind by the way? It could help me implementing it!

by the way, the last version (0.0.18) won't keep keys that were not explicitely declared in the object validator. Is that enough for you or do you really need it to fail if something else is passed?
