### ISSUE TITLE
An import path cannot end with a '.ts' extension.

### ISSUE THREAD

**Issue by webpapaya** [AlexGalays/validation.ts#5]
First of all thanks for the library. I'm getting the following error when using this package.

> An import path cannot end with a '.ts' extension. Consider importing 'validation' instead.

I think in newer versions of typescript .ts extensions are not allowed in module names. I have a feeling that this lib might need to change it's name in order to work with future TS versions. 
Factory.ts has similar issues: https://github.com/willryan/factory.ts/issues/8

**Comment by AlexGalays** [comment]
Sorry for not seeing this sooner.
This wasn't under my radar because there are ways to work around it (`moduleResolution`: 'true' in tsconfig.json should do it)
but I might as well change the name in the next version (done)

Cheers
